# Generated by Django 5.2.7 on 2025-11-09 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id_calificacion', models.AutoField(primary_key=True, serialize=False)),
                ('secuencia_de_evento', models.IntegerField()),
                ('dividendo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_historico', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_pago', models.DateField()),
                ('año', models.IntegerField()),
                ('descripcion', models.TextField()),
                ('isfut', models.BooleanField(default=False)),
                ('factor_actualizacion', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Ejercicio',
            fields=[
                ('id_ejercicio', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_ejercicio', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Factor',
            fields=[
                ('id_factor', models.AutoField(primary_key=True, serialize=False)),
                ('numero_factor', models.CharField(choices=[('Factor_8', 'Factor 8'), ('Factor_9', 'Factor 9'), ('Factor_10', 'Factor 10'), ('Factor_11', 'Factor 11'), ('Factor_12', 'Factor 12'), ('Factor_13', 'Factor 13'), ('Factor_14', 'Factor 14'), ('Factor_15', 'Factor 15'), ('Factor_16', 'Factor 16'), ('Factor_17', 'Factor 17'), ('Factor_18', 'Factor 18'), ('Factor_19', 'Factor 19'), ('Factor_20', 'Factor 20'), ('Factor_21', 'Factor 21'), ('Factor_22', 'Factor 22'), ('Factor_23', 'Factor 23'), ('Factor_24', 'Factor 24'), ('Factor_25', 'Factor 25'), ('Factor_26', 'Factor 26'), ('Factor_27', 'Factor 27'), ('Factor_28', 'Factor 28'), ('Factor_29', 'Factor 29'), ('Factor_30', 'Factor 30'), ('Factor_31', 'Factor 31'), ('Factor_32', 'Factor 32'), ('Factor_33', 'Factor 33'), ('Factor_34', 'Factor 34'), ('Factor_35', 'Factor 35'), ('Factor_36', 'Factor 36'), ('Factor_37', 'Factor 37')], max_length=20)),
                ('valor', models.DecimalField(decimal_places=8, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='Instrumento',
            fields=[
                ('id_instrumento', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_instrumento', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Mercado',
            fields=[
                ('id_mercado', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_mercado', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id_reporte', models.AutoField(primary_key=True, serialize=False)),
                ('accion', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoAgregacion',
            fields=[
                ('id_tipo_agregacion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_agregacion', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
