# Generated by Django 5.2.7 on 2025-11-09 10:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('calificaciones', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='calificacion',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='calificacion',
            name='ejercicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='calificaciones.ejercicio'),
        ),
        migrations.AddField(
            model_name='factor',
            name='calificacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factores', to='calificaciones.calificacion'),
        ),
        migrations.AddField(
            model_name='calificacion',
            name='instrumento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='calificaciones.instrumento'),
        ),
        migrations.AddField(
            model_name='instrumento',
            name='mercado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='calificaciones.mercado'),
        ),
        migrations.AddField(
            model_name='reporte',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='calificacion',
            name='tipo_agregacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='calificaciones.tipoagregacion'),
        ),
        migrations.AlterUniqueTogether(
            name='factor',
            unique_together={('calificacion', 'numero_factor')},
        ),
    ]
